version: '3.9'

services:
  image-generator:
    tty: true
    command: npm run dev
    volumes:
      - ./image-generator/src:/usr/src/app/src # To serve the image generator code in development
    profiles:
      - images
      - all
      - generator

  react-server:
    tty: true
    command: npm run dev
    volumes:
      - ./standalone-react/src:/usr/src/app/src # To serve the react server code in development
    profiles:
      - images
      - all

  react-client:
    tty: true
    command: npm run dev:standalone
    volumes:
      - ./plugin/includes/react-bracket-builder/src:/usr/src/app/src # To serve the react client code in development
    ports:
      - 8080:8080
    profiles:
      - images
      - all
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:8080']
      interval: 30s
      timeout: 10s
      retries: 5

  wp-app:
    tty: true
    build:
      context: .
      dockerfile: ./docker/wordpress/Dockerfile
      args:
        PLUGIN_NAME: wp-bracket-builder
    restart: unless-stopped
    environment:
      WORDPRESS_DB_HOST: wp-db
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_DEBUG: 1
      WORDPRESS_CONFIG_EXTRA: |
        define( 'WP_DEBUG_LOG', true );
        define( 'WP_DEBUG_DISPLAY', false );
        define('BRACKET_BUILDER_S3_IMAGE_BUCKET', 'wpbb-bracket-images-test1');
        define('BRACKET_BUILDER_S3_ORDER_BUCKET', 'wpbb-gelato-orders-test1');
        define('BRACKET_PRODUCT_CATEGORY', 'bracket-ready');
        define('BRACKET_PLACEMENT_CENTER_CAT', 'wpbb-placement-center');
        define('WP_SENTRY_ENV', 'production');
        define( 'WP_SENTRY_PHP_DSN', 'https://2e4df9ae93914f279c4ab59721811edc@o4505256728330240.ingest.sentry.io/4505256731082752' );
        define( 'WP_SENTRY_ERROR_TYPES', E_ALL & ~E_DEPRECATED & ~E_NOTICE & ~E_USER_DEPRECATED );
        define('AWS_ACCESS_KEY', '${AWS_ACCESS_KEY}');
        define('AWS_SECRET_KEY', '${AWS_SECRET_KEY}');
        define('MAILCHIMP_API_KEY','${MAILCHIMP_API_KEY}');
        define('MAILCHIMP_FROM_EMAIL','${MAILCHIMP_FROM_EMAIL}');
        define('WP_MEMORY_LIMIT', '512M');
      PLUGIN_NAME: wp-bracket-builder
      WORDPRESS_URL: http://localhost:8008
      WORDPRESS_TITLE: Wordpress
      WORDPRESS_ADMIN_USER: admin
      WORDPRESS_ADMIN_PASSWORD: admin
      WORDPRESS_ADMIN_EMAIL: test@wstrategies.co
    volumes:
      - ./plugin:/var/www/html/wp-content/plugins/wp-bracket-builder
      - wp-app-data:/var/www/html
    ports:
      - 8008:80
    depends_on:
      - wp-db
    profiles:
      - wp
      - all

  wp-db:
    tty: true
    image: mariadb
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
    volumes:
      - ./docker/db/scripts:/docker-entrypoint-initdb.d
      - wp-db-data:/var/lib/mysql
    ports:
      - 3308:3306
    profiles:
      - wp
      - all

  phpmyadmin:
    image: phpmyadmin
    restart: unless-stopped
    environment:
      PMA_HOST: wp-db
      PMA_PORT: 3306
      PMA_USER: wordpress
      PMA_PASSWORD: wordpress
    ports:
      - 8081:80
    depends_on:
      - wp-db
    profiles:
      - wp
      - all

networks:
  default:
    name: wp-bracket-builder

volumes:
  wp-app-data:
  wp-db-data:
