version: '3.9'

services:
  image-generator:
    tty: true
    command: npm run dev
    volumes:
      - ./image-generator/src:/usr/src/app/src

  react-server:
    tty: true
    command: npm run dev
    volumes:
      - ./standalone-react/src:/usr/src/app/src
      # - ./react-app/public:/usr/src/app/public
    ports:
      - 3001:3001
