version: '3.9'

services:
  image-generator:
    build:
      context: image-generator
      dockerfile: Dockerfile
    command: npm run start
    ports:
      - 3000:3000
    cap_add:
      - SYS_ADMIN
    depends_on:
      - react-server

  react-server:
    build:
      context: standalone-react
      dockerfile: Dockerfile
    command: npm run start
    depends_on:
      - react-client
    volumes:
      - react_dist:/usr/src/app/client/dist

  react-client:
    build:
      context: plugin/includes/react-bracket-builder
      dockerfile: Dockerfile
    command: npm run build:standalone
    volumes:
      - react_dist:/usr/src/app/dist

volumes:
  react_dist:


    