version: '3.9'

services:
  image-generator:
    build:
      context: image-generator
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    cap_add:
      - SYS_ADMIN
    depends_on:
      - react-app

  react-app:
    build:
      context: standalone-react
      dockerfile: Dockerfile
    