version: '3.9'

services:
  image-generator:
    build:
      context: image-generator
      dockerfile: Dockerfile
    command: npm run start
    restart: always
    ports:
      - 3000:3000
    cap_add:
      - SYS_ADMIN
    depends_on:
      - react-server
    environment:
      - CLIENT_URL=http://react-server:3001
      - AWS_REGION=us-east-1
    env_file:
      - .env
    volumes:
      - ~/.aws/credentials:/home/pptruser/.aws/credentials:ro
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:3000/ping']
      interval: 30s
      timeout: 10s
      retries: 5

  react-server:
    build:
      context: standalone-react
      dockerfile: Dockerfile
    command: npm run start
    restart: always
    depends_on:
      - react-client
    volumes:
      - react_dist:/usr/src/app/client/dist
    ports:
      - 3001:3001
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:3001/ping']
      interval: 30s
      timeout: 10s
      retries: 5

  react-client:
    build:
      context: plugin/Includes/react-bracket-builder
      dockerfile: Dockerfile
    command: npm run build:standalone
    volumes:
      - react_dist:/usr/src/app/build/standalone

volumes:
  react_dist:
