name: Default workflow

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

jobs:
  prettier-check:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 20
      - run: npm ci
      - run: npm run pretty:check
  wordpress-test:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - run: make wp-up-detach
      - run: make wp-install
      - run: docker exec wordpress-test-app composer install
      - run: make wp-test
      - run: make wp-down
        if: ${{ always() }}
