name: react-bracket-builder workflow

on:
  push:
    branches: ['main']
    paths:
      - 'plugin/includes/react-bracket-builder/**'
  pull_request:
    branches: ['main']
    paths:
      - 'plugin/includes/react-bracket-builder/**'

jobs:
  test:
    runs-on: [self-hosted]
    steps:
      - uses: actions/checkout@v3
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 20
      - run: npm ci --prefix plugin/includes/react-bracket-builder
      - run: npm run test --prefix plugin/includes/react-bracket-builder
