name: react-bracket-builder workflow

on:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: [self-hosted]
    steps:
      - uses: actions/checkout@v5
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 20
      - run: npm ci --prefix react-bracket-builder
      - run: npm run test --prefix react-bracket-builder
