name: wordpress workflow

on:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

env:
  PROJECT_NAME: github_runner
  SERVICE_NAME: wp-test-1

jobs:
  wordpress-tests:
    runs-on: [self-hosted]
    steps:
      - uses: actions/checkout@v5
      - run: docker compose -f compose.runner.yaml -p $PROJECT_NAME up --build --detach --remove-orphans
      - run: docker exec  ${{ env.PROJECT_NAME }}-${{ env.SERVICE_NAME }} composer install
      - run: docker exec ${{ env.PROJECT_NAME }}-${{ env.SERVICE_NAME }} install-wp-tests
      - run: docker exec ${{ env.PROJECT_NAME }}-${{ env.SERVICE_NAME }} composer test-integration
      - run: docker exec ${{ env.PROJECT_NAME }}-${{ env.SERVICE_NAME }} composer test-unit
      - run: docker compose -p $PROJECT_NAME down -v
        if: ${{ always() }}
  phpstan:
    runs-on: [self-hosted]
    steps:
      - uses: actions/checkout@v5
      - run: make composer-install
      - run: make phpstan-ci
